array_width = 20
fn_call_width = 80
binop_separator = "back"
blank_lines_upper_bound = 1
brace_style = "SameLineWhere"
chain_width = 100
max_width = 120
comment_width = 150
condense_wildcard_suffixes = true
edition = "2021"
empty_item_single_line = true
enum_discrim_align_threshold = 20
error_on_line_overflow = true
error_on_unformatted = true
fn_params_layout = "Tall"
fn_single_line = false
force_explicit_abi = true
format_code_in_doc_comments = true
doc_comment_code_block_width = 120
format_generated_files = true
format_macro_matchers = true
format_macro_bodies = true
format_strings = false
imports_layout = "HorizontalVertical"
indent_style = "Block"
match_arm_blocks = true
match_arm_leading_pipes = "Preserve"
match_block_trailing_comma = false
merge_derives = true
imports_granularity = "Module"
reorder_imports = true
reorder_impl_items = true
remove_nested_parens = true
short_array_element_width_threshold = 10
trailing_comma = "Never"
trailing_semicolon = false
use_try_shorthand = true
wrap_comments = true

